'use client';

import Link from 'next/link';
import { useEffect, useRef, useState } from 'react';
import QRCode from 'qrcode';
import { PDFDocument } from 'pdf-lib';

const META = {
  'pdf-merge':['PDF Merge','Merge multiple PDF files in your browser.'],
  'pdf-split':['PDF Split','Split a PDF into selected pages.'],
  'pdf-compressor':['PDF Compressor','Optimize and save a PDF locally.'],
  'image-to-pdf':['Image → PDF','Convert JPG/PNG images to PDF.'],
  'passport-photo-maker':['Passport Photo Maker','Create a square passport-style photo.'],
  'gpa-calculator':['GPA/CGPA Calculator','Calculate a weighted GPA from credits and grade points.'],
  'emi-calculator':['EMI Calculator','Calculate monthly loan EMI and total interest.'],
  'salary-calculator':['Salary Calculator','Estimate net salary after a simple deduction percentage.'],
  'tax-vat-calculator':['Tax/VAT Calculator','Calculate VAT and total amount.'],
  'invoice-generator':['Invoice Generator','Create a simple printable invoice.'],
  'cover-letter-builder':['Cover Letter Builder','Create a professional cover letter.'],
  'qr-scanner':['QR Scanner','Scan a QR code with a supported camera.'],
  'url-shortener':['URL Shortener','Shorten a URL using a public service.'],
  'json-formatter':['JSON Formatter','Format, validate and minify JSON.'],
  'favicon-generator':['Favicon Generator','Create a PNG favicon from an image.'],
  'meta-tag-generator':['Meta Tag Generator','Generate basic SEO meta tags.'],
  'sitemap-generator':['Sitemap Generator','Generate XML sitemap content.'],
  'password-strength-checker':['Password Strength Checker','Check password strength locally.'],
  'world-clock':['World Clock / Timezone','View current time across common time zones.'],
  'qr-generator':['QR Code Generator','Create a downloadable QR code.'],
  'password-generator':['Password Generator','Generate a strong random password.'],
  'word-counter':['Word Counter','Count words, characters and reading time.'],
  'age-calculator':['Age Calculator','Calculate exact age from a birth date.'],
  'date-calculator':['Date Calculator','Find the difference between two dates.'],
  'unit-converter':['Unit Converter','Convert common length and weight units.'],
  'percentage-calculator':['Percentage Calculator','Calculate a percentage of a value.'],
  'image-compressor':['Image Compressor','Compress an image locally in your browser.'],
  'currency-converter':['Currency Converter','Convert using a public exchange-rate service.'],
};

function Field({label,...props}){return <label className="field"><span>{label}</span><input {...props}/></label>}
function Button({children,onClick,light=false,disabled=false,type='button'}){return <button type={type} disabled={disabled} className="btn" style={light?{background:'#f2f4f7',color:'#344054'}:undefined} onClick={onClick}>{children}</button>}
function Upload({label,...props}){return <label className="upload">{label}<input type="file" {...props}/></label>}
function Download({data,name,type='text/plain'}){if(!data)return null;const href=data.startsWith('data:')?data:`data:${type};charset=utf-8,${encodeURIComponent(data)}`;return <a className="btn" href={href} download={name}>Download</a>}

function PDFMerge(){const[files,setFiles]=useState([]),[result,setResult]=useState('');async function run(){try{if(!files.length)return setResult('Select PDF files.');const out=await PDFDocument.create();for(const file of files){const doc=await PDFDocument.load(await file.arrayBuffer());(await out.copyPages(doc,doc.getPageIndices())).forEach(p=>out.addPage(p));}const url=URL.createObjectURL(new Blob([await out.save()],{type:'application/pdf'}));const a=document.createElement('a');a.href=url;a.download='merged.pdf';a.click();setResult('Merged PDF downloaded.');}catch{setResult('Could not read one of the PDF files.');}}return <><Upload label="Choose PDF files" accept="application/pdf" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))}/><Button onClick={run}>Merge PDFs</Button><p>{result}</p></>}
function PDFSplit(){const[file,setFile]=useState(null),[pages,setPages]=useState('1'),[result,setResult]=useState('');async function run(){try{if(!file)return setResult('Choose a PDF.');const doc=await PDFDocument.load(await file.arrayBuffer());const indexes=pages.split(',').map(v=>Number.parseInt(v.trim(),10)-1).filter(v=>Number.isInteger(v)&&v>=0&&v<doc.getPageCount());if(!indexes.length)return setResult('Enter valid page numbers.');const out=await PDFDocument.create();(await out.copyPages(doc,indexes)).forEach(p=>out.addPage(p));const url=URL.createObjectURL(new Blob([await out.save()],{type:'application/pdf'}));const a=document.createElement('a');a.href=url;a.download='selected-pages.pdf';a.click();setResult('Selected pages downloaded.');}catch{setResult('Invalid PDF.');}}return <><Upload label="Choose PDF" accept="application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><Field label="Pages (example: 1,3,5)" value={pages} onChange={e=>setPages(e.target.value)}/><Button onClick={run}>Split PDF</Button><p>{result}</p></>}
function ImageToPDF(){const[files,setFiles]=useState([]),[result,setResult]=useState('');async function run(){try{if(!files.length)return setResult('Choose JPG or PNG images.');const out=await PDFDocument.create();for(const file of files){const bytes=await file.arrayBuffer();const image=file.type==='image/png'?await out.embedPng(bytes):await out.embedJpg(bytes);const page=out.addPage([595,842]);const scale=Math.min(555/image.width,802/image.height);page.drawImage(image,{x:(595-image.width*scale)/2,y:(842-image.height*scale)/2,width:image.width*scale,height:image.height*scale});}const url=URL.createObjectURL(new Blob([await out.save()],{type:'application/pdf'}));const a=document.createElement('a');a.href=url;a.download='images.pdf';a.click();setResult('PDF downloaded.');}catch{setResult('Use JPG or PNG images.');}}return <><Upload label="Choose JPG/PNG images" accept="image/jpeg,image/png" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))}/><Button onClick={run}>Create PDF</Button><p>{result}</p></>}
function SimpleNumber({fields,calculate}){const initial=Object.fromEntries(fields.map(f=>[f.key,f.defaultValue??0])),[values,setValues]=useState(initial),[result,setResult]=useState('');return <>{fields.map(f=><Field key={f.key} label={f.label} type="number" step={f.step||'any'} value={values[f.key]} onChange={e=>setValues(v=>({...v,[f.key]:e.target.value}))}/>)}<Button onClick={()=>setResult(calculate(values))}>Calculate</Button>{result&&<div className="result">{result}</div>}</>}
function GPA(){const[rows,setRows]=useState([{c:3,g:4},{c:3,g:3.5}]),[result,setResult]=useState('');return <><p>Enter credits and grade points.</p>{rows.map((row,i)=><div className="row" key={i}><Field label="Credits" type="number" value={row.c} onChange={e=>setRows(a=>a.map((x,j)=>j===i?{...x,c:e.target.value}:x))}/><Field label="Grade points" type="number" step="0.01" value={row.g} onChange={e=>setRows(a=>a.map((x,j)=>j===i?{...x,g:e.target.value}:x))}/></div>)}<Button light onClick={()=>setRows(a=>[...a,{c:3,g:4}])}>Add subject</Button><Button onClick={()=>{const credits=rows.reduce((s,x)=>s+Number(x.c),0),points=rows.reduce((s,x)=>s+Number(x.c)*Number(x.g),0);setResult(`GPA: ${credits?(points/credits).toFixed(2):'0.00'}`)}}>Calculate GPA</Button>{result&&<div className="result">{result}</div>}</>}
function Invoice(){const[customer,setCustomer]=useState('Customer'),[items,setItems]=useState([{name:'Service',qty:1,price:100}]),total=items.reduce((s,x)=>s+Number(x.qty)*Number(x.price),0);return <><Field label="Customer" value={customer} onChange={e=>setCustomer(e.target.value)}/>{items.map((x,i)=><div className="row" key={i}><Field label="Item" value={x.name} onChange={e=>setItems(a=>a.map((v,j)=>j===i?{...v,name:e.target.value}:v))}/><Field label="Qty" type="number" value={x.qty} onChange={e=>setItems(a=>a.map((v,j)=>j===i?{...v,qty:e.target.value}:v))}/><Field label="Price" type="number" value={x.price} onChange={e=>setItems(a=>a.map((v,j)=>j===i?{...v,price:e.target.value}:v))}/></div>)}<Button light onClick={()=>setItems(a=>[...a,{name:'Service',qty:1,price:0}])}>Add item</Button><div className="result">Total: {total.toFixed(2)}</div><Button onClick={()=>window.print()}>Print / Save PDF</Button></>}
function Cover(){const[name,setName]=useState('Your Name'),[job,setJob]=useState('Job Title'),[company,setCompany]=useState('Company'),[result,setResult]=useState('');function run(){setResult(`Dear Hiring Manager,\n\nI am ${name}, and I am excited to apply for the ${job} position at ${company}. My skills, reliability and willingness to learn would allow me to contribute positively to your team.\n\nI would welcome the opportunity to discuss my application. Thank you for your consideration.\n\nSincerely,\n${name}`)}return <><Field label="Your name" value={name} onChange={e=>setName(e.target.value)}/><Field label="Job title" value={job} onChange={e=>setJob(e.target.value)}/><Field label="Company" value={company} onChange={e=>setCompany(e.target.value)}/><Button onClick={run}>Build Cover Letter</Button>{result&&<><textarea rows="12" value={result} readOnly/><Button light onClick={()=>navigator.clipboard?.writeText(result)}>Copy</Button></>}</>}
function QRGen(){const[text,setText]=useState('https://quicktoolbox.app'),[image,setImage]=useState('');return <><Field label="Text or URL" value={text} onChange={e=>setText(e.target.value)}/><Button onClick={async()=>setImage(await QRCode.toDataURL(text||' ',{width:320,margin:2}))}>Generate QR</Button>{image&&<><img src={image} alt="QR code" style={{width:240,display:'block',marginTop:16}}/><Download data={image} name="qr.png"/></>}</>}
function PasswordGenerator(){const[length,setLength]=useState(16),[password,setPassword]=useState('');function run(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*_-+=',values=new Uint32Array(Number(length)||16);crypto.getRandomValues(values);setPassword(Array.from(values,v=>chars[v%chars.length]).join(''));}return <><Field label="Length" type="number" min="6" max="64" value={length} onChange={e=>setLength(Math.max(6,Math.min(64,Number(e.target.value)||16)))}/><Button onClick={run}>Generate</Button>{password&&<><div className="password">{password}</div><Button light onClick={()=>navigator.clipboard?.writeText(password)}>Copy</Button></>}</>}
function WordCounter(){const[text,setText]=useState(''),words=(text.trim().match(/\S+/g)||[]).length;return <><textarea rows="12" value={text} onChange={e=>setText(e.target.value)} placeholder="Paste text…"/><div className="stats"><div><b>{words}</b><span>Words</span></div><div><b>{text.length}</b><span>Characters</span></div><div><b>{(text.match(/[.!?]+/g)||[]).length}</b><span>Sentences</span></div><div><b>{words?Math.ceil(words/200):0}</b><span>Min read</span></div></div></>}
function Age(){const[date,setDate]=useState('2000-01-01'),[result,setResult]=useState('');function run(){const birth=new Date(date),now=new Date();if(Number.isNaN(birth.getTime()))return setResult('Invalid date.');let y=now.getFullYear()-birth.getFullYear(),m=now.getMonth()-birth.getMonth(),d=now.getDate()-birth.getDate();if(d<0){m--;d+=new Date(now.getFullYear(),now.getMonth(),0).getDate();}if(m<0){y--;m+=12;}setResult(`${y} years, ${m} months, ${d} days`);}return <><Field label="Birth date" type="date" value={date} onChange={e=>setDate(e.target.value)}/><Button onClick={run}>Calculate age</Button>{result&&<div className="result">{result}</div>}</>}
function DateCalc(){const[a,setA]=useState('2026-01-01'),[b,setB]=useState('2026-08-19'),[result,setResult]=useState('');return <><Field label="Start date" type="date" value={a} onChange={e=>setA(e.target.value)}/><Field label="End date" type="date" value={b} onChange={e=>setB(e.target.value)}/><Button onClick={()=>{const x=new Date(a),y=new Date(b);if(Number.isNaN(x.getTime())||Number.isNaN(y.getTime()))return setResult('Invalid dates.');const days=Math.round(Math.abs(y-x)/86400000);setResult(`${days} days (${(days/7).toFixed(1)} weeks)`);}}>Calculate</Button>{result&&<div className="result">{result}</div>}</>}
function Units(){const[value,setValue]=useState(1),[from,setFrom]=useState('km'),[to,setTo]=useState('mi'),[result,setResult]=useState(''),units={mm:.001,cm:.01,m:1,km:1000,in:.0254,ft:.3048,yd:.9144,mi:1609.344,g:.001,kg:1,lb:.453592,oz:.0283495};function run(){if(from==='c'&&to==='f')return setResult((Number(value)*9/5+32).toFixed(4));if(from==='f'&&to==='c')return setResult(((Number(value)-32)*5/9).toFixed(4));if(!(from in units)||!(to in units))return setResult('Use compatible units.');setResult(((Number(value)*units[from])/units[to]).toFixed(6));}return <><Field label="Value" type="number" value={value} onChange={e=>setValue(e.target.value)}/><Field label="From (mm,cm,m,km,in,ft,yd,mi,g,kg,lb,oz,c,f)" value={from} onChange={e=>setFrom(e.target.value.toLowerCase())}/><Field label="To" value={to} onChange={e=>setTo(e.target.value.toLowerCase())}/><Button onClick={run}>Convert</Button>{result&&<div className="result">{result}</div>}</>}
function ImageCompress(){const[file,setFile]=useState(null),[quality,setQuality]=useState(.7),[output,setOutput]=useState('');function run(){if(!file)return;const image=new Image();image.onload=()=>{const canvas=document.createElement('canvas'),scale=Math.min(1,1600/Math.max(image.width,image.height));canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);setOutput(canvas.toDataURL('image/jpeg',Number(quality)||.7));};image.src=URL.createObjectURL(file);}return <><Upload label="Choose image" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/><Field label="Quality 0.1–1" type="number" min="0.1" max="1" step="0.1" value={quality} onChange={e=>setQuality(e.target.value)}/><Button onClick={run}>Compress</Button>{output&&<><img src={output} alt="Compressed preview" style={{maxWidth:'100%',marginTop:12}}/><Download data={output} name="compressed.jpg"/></>}</>}
function Currency(){const[amount,setAmount]=useState(100),[from,setFrom]=useState('USD'),[to,setTo]=useState('BDT'),[result,setResult]=useState(''),[busy,setBusy]=useState(false);async function run(){setBusy(true);try{const response=await fetch(`https://open.er-api.com/v6/latest/${encodeURIComponent(from.toUpperCase())}`),data=await response.json(),rate=data?.rates?.[to.toUpperCase()];if(!rate)throw new Error('rate');setResult(`${amount} ${from.toUpperCase()} = ${(Number(amount)*rate).toFixed(2)} ${to.toUpperCase()}`);}catch{setResult('Rate service unavailable. Try again later.');}finally{setBusy(false);}}return <><Field label="Amount" type="number" value={amount} onChange={e=>setAmount(e.target.value)}/><Field label="From" value={from} onChange={e=>setFrom(e.target.value)}/><Field label="To" value={to} onChange={e=>setTo(e.target.value)}/><Button disabled={busy} onClick={run}>{busy?'Converting…':'Convert'}</Button>{result&&<div className="result">{result}</div>}</>}
function QRScan(){const[value,setValue]=useState(''),videoRef=useRef(null),streamRef=useRef(null);async function start(){try{if(!('BarcodeDetector' in window))return setValue('BarcodeDetector is not supported in this browser.');const detector=new BarcodeDetector({formats:['qr_code']});streamRef.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});const video=videoRef.current;video.srcObject=streamRef.current;await video.play();const scan=async()=>{try{const codes=await detector.detect(video);if(codes[0]){setValue(codes[0].rawValue);streamRef.current?.getTracks().forEach(t=>t.stop());return;}}catch{}requestAnimationFrame(scan);};scan();}catch{setValue('Camera permission was denied or unavailable.');}}useEffect(()=>()=>streamRef.current?.getTracks().forEach(t=>t.stop()),[]);return <><video ref={videoRef} playsInline muted style={{width:'100%',maxWidth:420,borderRadius:12}}/><Button onClick={start}>Start Camera Scan</Button>{value&&<div className="result">{value}</div>}</>}
function Shortener(){const[url,setUrl]=useState('https://example.com'),[result,setResult]=useState(''),[busy,setBusy]=useState(false);async function run(){setBusy(true);try{const response=await fetch(`https://tinyurl.com/api-create.php?url=${encodeURIComponent(url)}`);setResult(await response.text());}catch{setResult('Shortening service unavailable.');}finally{setBusy(false);}}return <><Field label="Long URL" type="url" value={url} onChange={e=>setUrl(e.target.value)}/><Button disabled={busy} onClick={run}>{busy?'Shortening…':'Shorten URL'}</Button>{result&&<div className="result">{result}</div>}</>}
function JSONTool(){const[text,setText]=useState('{"name":"QuickToolBox","ok":true}'),[result,setResult]=useState('');function format(){try{setResult(JSON.stringify(JSON.parse(text),null,2));}catch(e){setResult(`Invalid JSON: ${e.message}`);}}function minify(){try{setResult(JSON.stringify(JSON.parse(text)));}catch(e){setResult(`Invalid JSON: ${e.message}`);}}return <><textarea rows="14" value={text} onChange={e=>setText(e.target.value)}/><div className="row"><Button onClick={format}>Format / Validate</Button><Button light onClick={minify}>Minify</Button></div>{result&&<textarea rows="14" value={result} readOnly/>}</>}
function Favicon(){const[file,setFile]=useState(null),[output,setOutput]=useState('');function run(){if(!file)return;const image=new Image();image.onload=()=>{const canvas=document.createElement('canvas');canvas.width=canvas.height=256;canvas.getContext('2d').drawImage(image,0,0,256,256);setOutput(canvas.toDataURL('image/png'));};image.src=URL.createObjectURL(file);}return <><Upload label="Choose image" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/><Button onClick={run}>Generate Favicon</Button>{output&&<><img src={output} alt="Favicon preview" style={{width:128,height:128}}/><Download data={output} name="favicon.png"/></>}</>}
function MetaTool(){const[title,setTitle]=useState('QuickToolBox'),[description,setDescription]=useState('Free useful online tools'),[url,setUrl]=useState('https://example.com'),[result,setResult]=useState('');function run(){setResult(`<title>${title}</title>\n<meta name="description" content="${description.replaceAll('"','&quot;')}">\n<link rel="canonical" href="${url}">\n<meta property="og:title" content="${title}">\n<meta property="og:description" content="${description.replaceAll('"','&quot;')}">\n<meta property="og:url" content="${url}">`);}return <><Field label="Title" value={title} onChange={e=>setTitle(e.target.value)}/><Field label="Description" value={description} onChange={e=>setDescription(e.target.value)}/><Field label="Canonical URL" value={url} onChange={e=>setUrl(e.target.value)}/><Button onClick={run}>Generate Tags</Button>{result&&<textarea rows="10" value={result} readOnly/>}</>}
function SitemapTool(){const[urls,setUrls]=useState('https://example.com/\nhttps://example.com/about'),[result,setResult]=useState('');function run(){const xml=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.split(/\n+/).filter(Boolean).map(u=>`  <url><loc>${u.trim()}</loc></url>`).join('\n')}\n</urlset>`;setResult(xml);}return <><textarea rows="10" value={urls} onChange={e=>setUrls(e.target.value)}/><Button onClick={run}>Generate Sitemap</Button>{result&&<><textarea rows="12" value={result} readOnly/><Download data={result} name="sitemap.xml" type="application/xml"/></>}</>}
function StrengthTool(){const[password,setPassword]=useState(''),[result,setResult]=useState('');function run(){let score=0;if(password.length>=8)score++;if(password.length>=12)score++;if(/[a-z]/.test(password)&&/[A-Z]/.test(password))score++;if(/\d/.test(password))score++;if(/[^A-Za-z0-9]/.test(password))score++;setResult(['Very weak','Weak','Fair','Good','Strong','Excellent'][score]);}return <><Field label="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><Button onClick={run}>Check Strength</Button>{result&&<div className="result">Strength: {result}</div>}</>}
function Clock(){const zones=['Asia/Dhaka','Asia/Kolkata','Asia/Dubai','Europe/London','Europe/Paris','America/New_York','America/Los_Angeles','Asia/Tokyo','Australia/Sydney'],[now,setNow]=useState(Date.now());useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);return <div className="grid">{zones.map(zone=><div className="card" key={zone}><h3>{zone}</h3><p>{new Intl.DateTimeFormat('en-US',{timeZone:zone,dateStyle:'medium',timeStyle:'medium'}).format(now)}</p></div>)}</div>}
function SimpleTool({slug}){const[value,setValue]=useState(''),[result,setResult]=useState('');if(slug==='json-formatter')return <JSONTool/>;if(slug==='meta-tag-generator')return <MetaTool/>;if(slug==='sitemap-generator')return <SitemapTool/>;if(slug==='password-strength-checker')return <StrengthTool/>;if(slug==='world-clock')return <Clock/>;if(slug==='qr-scanner')return <QRScan/>;if(slug==='url-shortener')return <Shortener/>;if(slug==='favicon-generator')return <Favicon/>;if(slug==='invoice-generator')return <Invoice/>;if(slug==='cover-letter-builder')return <Cover/>;if(slug==='qr-generator')return <QRGen/>;if(slug==='password-generator')return <PasswordGenerator/>;if(slug==='word-counter')return <WordCounter/>;if(slug==='age-calculator')return <Age/>;if(slug==='date-calculator')return <DateCalc/>;if(slug==='unit-converter')return <Units/>;if(slug==='percentage-calculator')return <SimpleNumber fields={[{key:'p',label:'Percent',defaultValue:25},{key:'n',label:'Value',defaultValue:200}]} calculate={v=>`${v.p}% of ${v.n} = ${(Number(v.p)*Number(v.n)/100).toFixed(4)}`}/>;if(slug==='image-compressor')return <ImageCompress/>;if(slug==='currency-converter')return <Currency/>;if(slug==='gpa-calculator')return <GPA/>;if(slug==='emi-calculator')return <SimpleNumber fields={[{key:'p',label:'Loan amount',defaultValue:500000},{key:'rate',label:'Annual interest %',defaultValue:10},{key:'years',label:'Years',defaultValue:5}]} calculate={v=>{const n=Number(v.years)*12,m=Number(v.rate)/1200,e=m?Number(v.p)*m*Math.pow(1+m,n)/(Math.pow(1+m,n)-1):Number(v.p)/n;return `Monthly EMI: ${e.toFixed(2)} | Total interest: ${(e*n-Number(v.p)).toFixed(2)}`}}/>;if(slug==='salary-calculator')return <SimpleNumber fields={[{key:'gross',label:'Gross salary',defaultValue:50000},{key:'ded',label:'Deductions %',defaultValue:10}]} calculate={v=>`Estimated net salary: ${(Number(v.gross)*(1-Number(v.ded)/100)).toFixed(2)}`}/>;if(slug==='tax-vat-calculator')return <SimpleNumber fields={[{key:'amount',label:'Amount',defaultValue:1000},{key:'vat',label:'VAT %',defaultValue:15}]} calculate={v=>{const tax=Number(v.amount)*Number(v.vat)/100;return `VAT: ${tax.toFixed(2)} | Total: ${(Number(v.amount)+tax).toFixed(2)}`}}/>;if(slug==='pdf-merge')return <PDFMerge/>;if(slug==='pdf-split')return <PDFSplit/>;if(slug==='image-to-pdf')return <ImageToPDF/>;if(slug==='pdf-compressor')return <PDFMerge/>;if(slug==='passport-photo-maker')return <Passport/>;return <><Field label="Enter value" value={value} onChange={e=>setValue(e.target.value)}/><Button onClick={()=>setResult(value||'Ready')}>Process</Button>{result&&<div className="result">{result}</div>}</>}
export default function ToolClient({slug}){const meta=META[slug]||['Tool not found','This tool is not available.'];return <><header><Link className="brand" href="/"><b>Q</b> QuickToolBox</Link><Link href="/">← All tools</Link></header><main className="tool"><small>FREE ONLINE TOOL</small><h1>{meta[0]}</h1><p>{meta[1]}</p><div className="box"><SimpleTool slug={slug}/></div></main><footer>© 2026 QuickToolBox</footer></>}
