'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import QRCode from 'qrcode';
import {PDFDocument} from 'pdf-lib';
const META={
'pdf-merge':['PDF Merge','Merge multiple PDF files in your browser.'],'pdf-split':['PDF Split','Extract selected pages from a PDF.'],'pdf-compressor':['PDF Compressor','Optimize and save a PDF locally.'],'image-to-pdf':['Image → PDF','Convert JPG/PNG images to PDF.'],'passport-photo-maker':['Passport Photo Maker','Create a standard square passport photo.'],'gpa-calculator':['GPA/CGPA Calculator','Calculate a weighted GPA.'],'emi-calculator':['EMI Calculator','Calculate monthly loan EMI and interest.'],'salary-calculator':['Salary Calculator','Estimate net salary after deductions.'],'tax-vat-calculator':['Tax/VAT Calculator','Calculate VAT and total amount.'],'invoice-generator':['Invoice Generator','Create and print a simple invoice.'],'cover-letter-builder':['Cover Letter Builder','Generate a professional cover letter.'],'qr-scanner':['QR Scanner','Scan a QR code with a supported camera.'],'url-shortener':['URL Shortener','Shorten a URL using a public service.'],'json-formatter':['JSON Formatter','Format, validate and minify JSON.'],'favicon-generator':['Favicon Generator','Create a favicon from an image.'],'meta-tag-generator':['Meta Tag Generator','Generate SEO meta tags.'],'sitemap-generator':['Sitemap Generator','Generate XML sitemap content.'],'password-strength-checker':['Password Strength Checker','Check password strength locally.'],'world-clock':['World Clock / Timezone','View current time across major time zones.']};
const Field=({label,...p})=><label className="field"><span>{label}</span><input {...p}/></label>;
const Button=({children,onClick,light=false})=><button className="btn" style={light?{background:'#f2f4f7',color:'#344054'}:{}} onClick={onClick}>{children}</button>;
const Upload=({label,...p})=><label className="upload">{label}<input type="file" {...p}/></label>;
const Download=({data,name,type='text/plain'})=><a className="btn" href={data?.startsWith('data:')?data:`data:${type};charset=utf-8,${encodeURIComponent(data||'')}`} download={name}>Download</a>;
function saveBlob(bytes,name,type){const u=URL.createObjectURL(new Blob([bytes],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function Merge(){const[fs,setFs]=useState([]),[r,setR]=useState('');return <><Upload label="Choose PDF files" accept="application/pdf" multiple onChange={e=>setFs([...e.target.files])}/><Button onClick={async()=>{try{const o=await PDFDocument.create();for(const f of fs){const d=await PDFDocument.load(await f.arrayBuffer());(await o.copyPages(d,d.getPageIndices())).forEach(p=>o.addPage(p))}saveBlob(await o.save(),'merged.pdf','application/pdf');setR('Merged PDF downloaded.')}catch{setR('Select valid PDF files.')}}}>Merge PDFs</Button><p>{r}</p></>}
function Split(){const[f,setF]=useState(null),[pages,setPages]=useState('1'),[r,setR]=useState('');return <><Upload label="Choose PDF" accept="application/pdf" onChange={e=>setF(e.target.files?.[0])}/><Field label="Pages e.g. 1,3,5" value={pages} onChange={e=>setPages(e.target.value)}/><Button onClick={async()=>{try{const d=await PDFDocument.load(await f.arrayBuffer()),n=pages.split(',').map(x=>+x.trim()-1).filter(x=>x>=0&&x<d.getPageCount()),o=await PDFDocument.create();(await o.copyPages(d,n)).forEach(p=>o.addPage(p));saveBlob(await o.save(),'split-pages.pdf','application/pdf');setR('Selected pages downloaded.')}catch{setR('Invalid PDF or page numbers.')}}}>Split PDF</Button><p>{r}</p></>}
function Compress(){const[f,setF]=useState(null);return <><Upload label="Choose PDF" accept="application/pdf" onChange={e=>setF(e.target.files?.[0])}/><Button onClick={async()=>{if(!f)return;const d=await PDFDocument.load(await f.arrayBuffer());saveBlob(await d.save({useObjectStreams:true}),'optimized.pdf','application/pdf')}}>Optimize PDF</Button><small>Browser optimization may not reduce every PDF.</small></>}
function ImagePDF(){const[fs,setFs]=useState([]);return <><Upload label="Choose JPG/PNG images" accept="image/jpeg,image/png" multiple onChange={e=>setFs([...e.target.files])}/><Button onClick={async()=>{const o=await PDFDocument.create();for(const f of fs){const b=await f.arrayBuffer(),im=f.type==='image/png'?await o.embedPng(b):await o.embedJpg(b),p=o.addPage([595,842]),s=Math.min(555/im.width,802/im.height);p.drawImage(im,{x:(595-im.width*s)/2,y:(842-im.height*s)/2,width:im.width*s,height:im.height*s})}saveBlob(await o.save(),'images.pdf','application/pdf')}}>Create PDF</Button></>}
function Passport(){const[f,setF]=useState(null),[o,setO]=useState('');return <><Upload label="Choose portrait" accept="image/*" onChange={e=>setF(e.target.files?.[0])}/><Button onClick={()=>{if(!f)return;const im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=c.height=600;const x=c.getContext('2d'),s=Math.max(600/im.width,600/im.height),w=im.width*s,h=im.height*s;x.drawImage(im,(600-w)/2,(600-h)/2,w,h);setO(c.toDataURL('image/jpeg',.92))};im.src=URL.createObjectURL(f)}}>Make Photo</Button>{o&&<><img src={o} alt="Passport photo" style={{maxWidth:280}}/><Download data={o} name="passport-photo.jpg"/></>}</>}
function GPA(){const[rows,setRows]=useState([{c:3,g:4},{c:3,g:3.5}]),[r,setR]=useState('');return <>{rows.map((x,i)=><div className="row" key={i}><Field label="Credits" type="number" value={x.c} onChange={e=>{const a=[...rows];a[i]={...a[i],c:e.target.value};setRows(a)}}/><Field label="Grade points" type="number" step=".01" value={x.g} onChange={e=>{const a=[...rows];a[i]={...a[i],g:e.target.value};setRows(a)}}/></div>)}<Button light onClick={()=>setRows([...rows,{c:3,g:4}])}>Add subject</Button><Button onClick={()=>{const c=rows.reduce((a,x)=>a+Number(x.c),0),p=rows.reduce((a,x)=>a+Number(x.c)*Number(x.g),0);setR(c?(p/c).toFixed(2):'0')}}>Calculate GPA</Button>{r&&<div className="result">GPA: {r}</div>}</>}
function EMI(){const[p,setP]=useState(500000),[rate,setRate]=useState(10),[years,setYears]=useState(5),[r,setR]=useState('');return <><Field label="Loan amount" type="number" value={p} onChange={e=>setP(e.target.value)}/><Field label="Annual interest %" type="number" value={rate} onChange={e=>setRate(e.target.value)}/><Field label="Years" type="number" value={years} onChange={e=>setYears(e.target.value)}/><Button onClick={()=>{const n=Number(years)*12,m=Number(rate)/1200,e=m?Number(p)*m*(1+m)**n/((1+m)**n-1):Number(p)/n;setR(`Monthly EMI: ${e.toFixed(2)} | Interest: ${(e*n-Number(p)).toFixed(2)}`)}}>Calculate EMI</Button>{r&&<div className="result">{r}</div>}</>}
function Salary(){const[g,setG]=useState(50000),[d,setD]=useState(10),[r,setR]=useState('');return <><Field label="Gross salary" type="number" value={g} onChange={e=>setG(e.target.value)}/><Field label="Deductions %" type="number" value={d} onChange={e=>setD(e.target.value)}/><Button onClick={()=>setR(`Estimated net salary: ${(Number(g)*(1-Number(d)/100)).toFixed(2)}`)}>Calculate</Button>{r&&<div className="result">{r}</div>}</>}
function Tax(){const[a,setA]=useState(1000),[v,setV]=useState(15),[r,setR]=useState('');return <><Field label="Amount" type="number" value={a} onChange={e=>setA(e.target.value)}/><Field label="VAT %" type="number" value={v} onChange={e=>setV(e.target.value)}/><Button onClick={()=>{const t=Number(a)*Number(v)/100;setR(`VAT: ${t.toFixed(2)} | Total: ${(Number(a)+t).toFixed(2)}`)}}>Calculate VAT</Button>{r&&<div className="result">{r}</div>}</>}
function Invoice(){const[c,setC]=useState('Customer'),[items,setItems]=useState([{n:'Service',q:1,p:100}]),total=items.reduce((a,x)=>a+Number(x.q)*Number(x.p),0);return <><Field label="Customer" value={c} onChange={e=>setC(e.target.value)}/>{items.map((x,i)=><div className="row" key={i}><Field label="Item" value={x.n} onChange={e=>{const a=[...items];a[i]={...a[i],n:e.target.value};setItems(a)}}/><Field label="Qty" type="number" value={x.q} onChange={e=>{const a=[...items];a[i]={...a[i],q:e.target.value};setItems(a)}}/><Field label="Price" type="number" value={x.p} onChange={e=>{const a=[...items];a[i]={...a[i],p:e.target.value};setItems(a)}}/></div>)}<Button light onClick={()=>setItems([...items,{n:'Service',q:1,p:0}])}>Add item</Button><div className="result">Total: {total.toFixed(2)}</div><Button onClick={()=>window.print()}>Print / Save PDF</Button></>}
function Cover(){const[n,setN]=useState('Your Name'),[j,setJ]=useState('Job Title'),[c,setC]=useState('Company'),[r,setR]=useState('');return <><Field label="Your name" value={n} onChange={e=>setN(e.target.value)}/><Field label="Job title" value={j} onChange={e=>setJ(e.target.value)}/><Field label="Company" value={c} onChange={e=>setC(e.target.value)}/><Button onClick={()=>setR(`Dear Hiring Manager,\n\nI am ${n}, and I am excited to apply for the ${j} position at ${c}. My skills, reliability and willingness to learn would allow me to contribute positively to your team.\n\nSincerely,\n${n}`)}>Build Cover Letter</Button>{r&&<textarea rows="12" value={r} readOnly/>}</>}
function QRScan(){const[v,setV]=useState(''),ref=useRef(null),stream=useRef(null);async function start(){try{if(!('BarcodeDetector'in window))return setV('BarcodeDetector is not supported in this browser.');stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});const video=ref.current;video.srcObject=stream.current;await video.play();const d=new BarcodeDetector({formats:['qr_code']});const loop=async()=>{try{const a=await d.detect(video);if(a[0]){setV(a[0].rawValue);stream.current?.getTracks().forEach(t=>t.stop());return}}catch{}requestAnimationFrame(loop)};loop()}catch{setV('Camera permission denied or unavailable.')}}return <><video ref={ref} playsInline muted style={{width:'100%',maxWidth:420}}/><Button onClick={start}>Start Camera Scan</Button>{v&&<div className="result">{v}</div>}</>}
function Shortener(){const[u,setU]=useState('https://example.com'),[r,setR]=useState('');return <><Field label="Long URL" type="url" value={u} onChange={e=>setU(e.target.value)}/><Button onClick={async()=>{try{const x=await fetch(`https://tinyurl.com/api-create.php?url=${encodeURIComponent(u)}`);setR(await x.text())}catch{setR('Shortening service unavailable.')}}}>Shorten URL</Button>{r&&<div className="result">{r}</div>}</>}
function JSONTool(){const[t,setT]=useState('{"name":"QuickToolBox","ok":true}'),[r,setR]=useState('');const run=min=>{try{setR(JSON.stringify(JSON.parse(t),null,min?0:2))}catch(e){setR('Invalid JSON: '+e.message)}};return <><textarea rows="14" value={t} onChange={e=>setT(e.target.value)}/><Button onClick={()=>run(false)}>Format / Validate</Button><Button light onClick={()=>run(true)}>Minify</Button>{r&&<textarea rows="14" value={r} readOnly/>}</>}
function Favicon(){const[f,setF]=useState(null),[o,setO]=useState('');return <><Upload label="Choose image" accept="image/*" onChange={e=>setF(e.target.files?.[0])}/><Button onClick={()=>{if(!f)return;const im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=c.height=256;c.getContext('2d').drawImage(im,0,0,256,256);setO(c.toDataURL('image/png'))};im.src=URL.createObjectURL(f)}}>Generate Favicon</Button>{o&&<Download data={o} name="favicon.png"/>}</>}
function Meta(){const[t,setT]=useState('QuickToolBox'),[d,setD]=useState('Free useful online tools'),[u,setU]=useState('https://example.com'),[r,setR]=useState('');return <><Field label="Title" value={t} onChange={e=>setT(e.target.value)}/><Field label="Description" value={d} onChange={e=>setD(e.target.value)}/><Field label="Canonical URL" value={u} onChange={e=>setU(e.target.value)}/><Button onClick={()=>setR(`<title>${t}</title>\n<meta name="description" content="${d.replaceAll('"','&quot;')}">\n<link rel="canonical" href="${u}">`)}>Generate Tags</Button>{r&&<textarea rows="8" value={r} readOnly/>}</>}
function Sitemap(){const[u,setU]=useState('https://example.com/\nhttps://example.com/about'),[r,setR]=useState('');return <><textarea rows="10" value={u} onChange={e=>setU(e.target.value)}/><Button onClick={()=>setR(`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${u.split(/\n+/).filter(Boolean).map(x=>`<url><loc>${x.trim()}</loc></url>`).join('\n')}\n</urlset>`)}>Generate Sitemap</Button>{r&&<><textarea rows="12" value={r} readOnly/><Download data={r} name="sitemap.xml" type="application/xml"/></>}</>}
function Strength(){const[p,setP]=useState(''),[r,setR]=useState('');return <><Field label="Password" type="password" value={p} onChange={e=>setP(e.target.value)}/><Button onClick={()=>{let s=0;if(p.length>=8)s++;if(p.length>=12)s++;if(/[a-z]/.test(p)&&/[A-Z]/.test(p))s++;if(/\d/.test(p))s++;if(/[^A-Za-z0-9]/.test(p))s++;setR(['Very weak','Weak','Fair','Good','Strong','Excellent'][s])}}>Check Strength</Button>{r&&<div className="result">Strength: {r}</div>}</>}
function Clock(){const z=['Asia/Dhaka','Asia/Kolkata','Asia/Dubai','Europe/London','Europe/Paris','America/New_York','America/Los_Angeles','Asia/Tokyo','Australia/Sydney'],[t,setT]=useState(Date.now());useEffect(()=>{const i=setInterval(()=>setT(Date.now()),1000);return()=>clearInterval(i)},[]);return <div className="grid">{z.map(x=><div className="card" key={x}><h3>{x}</h3><p>{new Intl.DateTimeFormat('en-US',{timeZone:x,dateStyle:'medium',timeStyle:'medium'}).format(t)}</p></div>)}</div>}
const MAP={'pdf-merge':Merge,'pdf-split':Split,'pdf-compressor':Compress,'image-to-pdf':ImagePDF,'passport-photo-maker':Passport,'gpa-calculator':GPA,'emi-calculator':EMI,'salary-calculator':Salary,'tax-vat-calculator':Tax,'invoice-generator':Invoice,'cover-letter-builder':Cover,'qr-scanner':QRScan,'url-shortener':Shortener,'json-formatter':JSONTool,'favicon-generator':Favicon,'meta-tag-generator':Meta,'sitemap-generator':Sitemap,'password-strength-checker':Strength,'world-clock':Clock};
export default function ToolClient({slug}){const C=MAP[slug],m=META[slug]||['Tool not found',''];return <><header><Link className="brand" href="/"><b>Q</b> QuickToolBox</Link><Link href="/">← All tools</Link></header><main className="tool"><small>FREE ONLINE TOOL</small><h1>{m[0]}</h1><p>{m[1]}</p><div className="box">{C?<C/>:<p>Tool not found.</p>}</div></main><footer>© 2026 QuickToolBox</footer></>}
