'use client';
import Link from 'next/link';
import {useState,useRef,useEffect} from 'react';
import QRCode from 'qrcode';
import {PDFDocument} from 'pdf-lib';
const META={
'pdf-merge':['PDF Merge','Merge multiple PDF files in your browser.'],'pdf-split':['PDF Split','Split a PDF into selected pages.'],'pdf-compressor':['PDF Compressor','Optimize and save a PDF locally.'],'image-to-pdf':['Image → PDF','Convert images to PDF.'],'passport-photo-maker':['Passport Photo Maker','Create a 2×2 inch passport photo.'],'gpa-calculator':['GPA/CGPA Calculator','Calculate GPA or CGPA.'],'emi-calculator':['EMI Calculator','Calculate monthly loan EMI.'],'salary-calculator':['Salary Calculator','Estimate net salary.'],'tax-vat-calculator':['Tax/VAT Calculator','Calculate VAT and simple tax estimates.'],'invoice-generator':['Invoice Generator','Create and print an invoice.'],'cover-letter-builder':['Cover Letter Builder','Create a professional cover letter.'],'qr-scanner':['QR Scanner','Scan QR codes with a supported camera.'],'url-shortener':['URL Shortener','Shorten a URL with a public service.'],'json-formatter':['JSON Formatter','Format, validate and minify JSON.'],'favicon-generator':['Favicon Generator','Create a favicon from an image.'],'meta-tag-generator':['Meta Tag Generator','Generate SEO meta tags.'],'sitemap-generator':['Sitemap Generator','Generate XML sitemap content.'],'password-strength-checker':['Password Strength Checker','Check password strength locally.'],'world-clock':['World Clock / Timezone','View current time across time zones.']};
const Field=({label,...p})=><label className="field"><span>{label}</span><input {...p}/></label>;
const Button=({children,onClick,light=false})=><button className="btn" style={light?{background:'#f2f4f7',color:'#344054'}:{}} onClick={onClick}>{children}</button>;
const Download=({data,name,type='text/plain'})=><a className="btn" href={data?.startsWith('data:')?data:`data:${type};charset=utf-8,${encodeURIComponent(data||'')}`} download={name}>Download</a>;
function PDFMerge(){const[fs,setFs]=useState([]),[r,setR]=useState('');async function go(){try{if(!fs.length)return setR('Select PDF files.');const out=await PDFDocument.create();for(const f of fs){const d=await PDFDocument.load(await f.arrayBuffer());(await out.copyPages(d,d.getPageIndices())).forEach(p=>out.addPage(p))}const u=URL.createObjectURL(new Blob([await out.save()],{type:'application/pdf'}));const a=document.createElement('a');a.href=u;a.download='merged.pdf';a.click();setR('Merged PDF downloaded.')}catch(e){setR('Could not read a PDF.')}}return <><Upload label="Choose PDF files" accept="application/pdf" multiple onChange={e=>setFs(Array.from(e.target.files||[]))}/><Button onClick={go}>Merge PDFs</Button><p>{r}</p></>}
function PDFSplit(){const[f,setF]=useState(null),[page,setPage]=useState('1'),[r,setR]=useState('');async function go(){try{if(!f)return setR('Choose a PDF.');const d=await PDFDocument.load(await f.arrayBuffer()),nums=page.split(',').map(x=>parseInt(x.trim(),10)-1).filter(x=>x>=0&&x<d.getPageCount());if(!nums.length)return setR('Enter valid page numbers.');const out=await PDFDocument.create();(await out.copyPages(d,nums)).forEach(p=>out.addPage(p));const u=URL.createObjectURL(new Blob([await out.save()],{type:'application/pdf'}));const a=document.createElement('a');a.href=u;a.download='split-pages.pdf';a.click();setR('Selected pages downloaded.')}catch{setR('Invalid PDF.')}}return <><Upload label="Choose PDF" accept="application/pdf" onChange={e=>setF(e.target.files?.[0])}/><Field label="Pages (example: 1,3,5)" value={page} onChange={e=>setPage(e.target.value)}/><Button onClick={go}>Split PDF</Button><p>{r}</p></>}
function PDFCompress(){const[f,setF]=useState(null),[r,setR]=useState('');async function go(){try{if(!f)return setR('Choose a PDF.');const d=await PDFDocument.load(await f.arrayBuffer());const bytes=await d.save({useObjectStreams:true,addDefaultPage:false});const u=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));const a=document.createElement('a');a.href=u;a.download='optimized.pdf';a.click();setR(`Saved optimized PDF (${Math.round(bytes.length/1024)} KB).`)}catch{setR('Could not optimize this PDF.')}}return <><Upload label="Choose PDF" accept="application/pdf" onChange={e=>setF(e.target.files?.[0])}/><Button onClick={go}>Optimize PDF</Button><p>{r}</p><small>Browser optimization cannot guarantee a smaller file for every PDF.</small></>}
function ImagePDF(){const[fs,setFs]=useState([]),[r,setR]=useState('');async function go(){try{if(!fs.length)return setR('Choose images.');const out=await PDFDocument.create();for(const f of fs){const bytes=await f.arrayBuffer();let im; if(f.type==='image/png') im=await out.embedPng(bytes); else im=await out.embedJpg(bytes);const p=out.addPage([595,842]);const s=Math.min(555/im.width,802/im.height);p.drawImage(im,{x:(595-im.width*s)/2,y:(842-im.height*s)/2,width:im.width*s,height:im.height*s})}const u=URL.createObjectURL(new Blob([await out.save()],{type:'application/pdf'}));const a=document.createElement('a');a.href=u;a.download='images.pdf';a.click();setR('PDF downloaded.')}catch{setR('Use JPG or PNG images.')}}return <><Upload label="Choose JPG/PNG images" accept="image/jpeg,image/png" multiple onChange={e=>setFs(Array.from(e.target.files||[]))}/><Button onClick={go}>Create PDF</Button><p>{r}</p></>}
function Passport(){const[f,setF]=useState(null),[o,setO]=useState('');function go(){if(!f)return;const im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=600;c.height=600;const x=c.getContext('2d'),s=Math.max(600/im.width,600/im.height);const w=im.width*s,h=im.height*s;x.drawImage(im,(600-w)/2,(600-h)/2,w,h);setO(c.toDataURL('image/jpeg',.92))};im.src=URL.createObjectURL(f)}return <><Upload label="Choose portrait" accept="image/*" onChange={e=>setF(e.target.files?.[0])}/><Button onClick={go}>Make Photo</Button>{o&&<><img src={o} alt="Passport photo" style={{maxWidth:'280px',display:'block',marginTop:16}}/><Download data={o} name="passport-photo.jpg"/></>}</>}
function GPA(){const[rows,setRows]=useState([{c:3,g:4},{c:3,g:3.5}]),[r,setR]=useState('');return <><p>Enter credit and grade points.</p>{rows.map((x,i)=><div className="row" key={i}><Field label="Credits" type="number" value={x.c} onChange={e=>{const a=[...rows];a[i].c=e.target.value;setRows(a)}}/><Field label="Grade points" type="number" step="0.01" value={x.g} onChange={e=>{const a=[...rows];a[i].g=e.target.value;setRows(a)}}/></div>)}<Button light onClick={()=>setRows([...rows,{c:3,g:4}])}>Add subject</Button><Button onClick={()=>{const c=rows.reduce((a,x)=>a+Number(x.c),0),p=rows.reduce((a,x)=>a+Number(x.c)*Number(x.g),0);setR(c?(p/c).toFixed(2):'0')}}>Calculate GPA</Button>{r&&<div className="result">GPA: {r}</div>}</>}
function EMI(){const[p,setP]=useState(500000),[rate,setRate]=useState(10),[years,setYears]=useState(5),[r,setR]=useState('');function go(){const n=years*12,m=rate/1200,e=m?Number(p)*m*Math.pow(1+m,n)/(Math.pow(1+m,n)-1):Number(p)/n;setR(`Monthly EMI: ${e.toFixed(2)} | Total interest: ${(e*n-p).toFixed(2)}`)}return <><Field label="Loan amount" type="number" value={p} onChange={e=>setP(e.target.value)}/><Field label="Annual interest %" type="number" value={rate} onChange={e=>setRate(e.target.value)}/><Field label="Years" type="number" value={years} onChange={e=>setYears(e.target.value)}/><Button onClick={go}>Calculate EMI</Button>{r&&<div className="result">{r}</div>}</>}
function Salary(){const[g,setG]=useState(50000),[ded,setD]=useState(10),[r,setR]=useState('');return <><Field label="Gross salary" type="number" value={g} onChange={e=>setG(e.target.value)}/><Field label="Deductions %" type="number" value={ded} onChange={e=>setD(e.target.value)}/><Button onClick={()=>{const n=Number(g)*(1-Number(ded)/100);setR(`Estimated net salary: ${n.toFixed(2)}`)}}>Calculate</Button>{r&&<div className="result">{r}</div>}<small>Generic estimate; payroll rules vary by country and employer.</small></>}
function TaxVAT(){const[a,setA]=useState(1000),[v,setV]=useState(15),[r,setR]=useState('');return <><Field label="Amount" type="number" value={a} onChange={e=>setA(e.target.value)}/><Field label="VAT %" type="number" value={v} onChange={e=>setV(e.target.value)}/><Button onClick={()=>{const tax=Number(a)*Number(v)/100;setR(`VAT: ${tax.toFixed(2)} | Total: ${(Number(a)+tax).toFixed(2)}`)}}>Calculate VAT</Button>{r&&<div className="result">{r}</div>}<small>VAT calculator only; income-tax liability requires jurisdiction-specific rules.</small></>}
function Invoice(){const[c,setC]=useState('Customer'),[items,setItems]=useState([{n:'Service',q:1,p:100}]);const total=items.reduce((a,x)=>a+Number(x.q)*Number(x.p),0);return <><Field label="Customer" value={c} onChange={e=>setC(e.target.value)}/>{items.map((x,i)=><div className="row" key={i}><Field label="Item" value={x.n} onChange={e=>{const a=[...items];a[i].n=e.target.value;setItems(a)}}/><Field label="Qty" type="number" value={x.q} onChange={e=>{const a=[...items];a[i].q=e.target.value;setItems(a)}}/><Field label="Price" type="number" value={x.p} onChange={e=>{const a=[...items];a[i].p=e.target.value;setItems(a)}}/></div>)}<Button light onClick={()=>setItems([...items,{n:'Service',q:1,p:0}])}>Add item</Button><div className="result">Total: {total.toFixed(2)}</div><Button onClick={()=>window.print()}>Print / Save PDF</Button></>}
function Cover(){const[n,setN]=useState('Your Name'),[j,setJ]=useState('Job Title'),[co,setCo]=useState('Company'),[r,setR]=useState('');return <><Field label="Your name" value={n} onChange={e=>setN(e.target.value)}/><Field label="Job title" value={j} onChange={e=>setJ(e.target.value)}/><Field label="Company" value={co} onChange={e=>setCo(e.target.value)}/><Button onClick={()=>setR(`Dear Hiring Manager,\n\nI am ${n}, and I am excited to apply for the ${j} position at ${co}. My skills, reliability and willingness to learn would allow me to contribute positively to your team.\n\nI would welcome the opportunity to discuss my application. Thank you for your consideration.\n\nSincerely,\n${n}`)}>Build Cover Letter</Button>{r&&<textarea rows="12" value={r} readOnly/>}<Button light onClick={()=>r&&navigator.clipboard?.writeText(r)}>Copy</Button></>}
function QRScan(){const[v,setV]=useState(''),ref=useRef(null),stream=useRef(null);async function start(){try{if(!('BarcodeDetector' in window))return setV('This browser does not support BarcodeDetector. Use a QR scanner app/browser that supports it.');const d=new BarcodeDetector({formats:['qr_code']});stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});const video=ref.current;video.srcObject=stream.current;await video.play();const scan=async()=>{try{const a=await d.detect(video);if(a[0]){setV(a[0].rawValue);stream.current?.getTracks().forEach(t=>t.stop());return}}catch{}requestAnimationFrame(scan)};scan()}catch{setV('Camera permission was denied or unavailable.')}}return <><video ref={ref} playsInline muted style={{width:'100%',maxWidth:420,borderRadius:12}}/><Button onClick={start}>Start Camera Scan</Button>{v&&<div className="result">{v}</div>}</>}
function Shortener(){const[u,setU]=useState('https://example.com'),[r,setR]=useState(''),[busy,setB]=useState(false);return <><Field label="Long URL" type="url" value={u} onChange={e=>setU(e.target.value)}/><Button onClick={async()=>{setB(true);try{const x=await fetch(`https://tinyurl.com/api-create.php?url=${encodeURIComponent(u)}`);setR(await x.text())}catch{setR('Shortening service unavailable.')}finally{setB(false)}}}>{busy?'Shortening…':'Shorten URL'}</Button>{r&&<div className="result">{r}</div>}</>}
function JSONTool(){const[t,setT]=useState('{"name":"QuickToolBox","ok":true}'),[r,setR]=useState('');return <><textarea rows="14" value={t} onChange={e=>setT(e.target.value)}/><div className="row"><Button onClick={()=>{try{setR(JSON.stringify(JSON.parse(t),null,2))}catch(e){setR('Invalid JSON: '+e.message)}}}>Format / Validate</Button><Button light onClick={()=>{try{setR(JSON.stringify(JSON.parse(t)))}catch(e){setR('Invalid JSON: '+e.message)}}}>Minify</Button></div>{r&&<textarea rows="14" value={r} readOnly/>}</>}
function Favicon(){const[f,setF]=useState(null),[o,setO]=useState('');function go(){if(!f)return;const im=new Image();im.onload=()=>{const c=document.createElement('canvas');c.width=c.height=256;c.getContext('2d').drawImage(im,0,0,256,256);setO(c.toDataURL('image/png'))};im.src=URL.createObjectURL(f)}return <><Upload label="Choose image" accept="image/*" onChange={e=>setF(e.target.files?.[0])}/><Button onClick={go}>Generate Favicon</Button>{o&&<><img src={o} alt="Favicon preview" style={{width:128,height:128}}/><Download data={o} name="favicon.png"/></>}</>}
function Meta(){const[t,setT]=useState('QuickToolBox'),[d,setD]=useState('Free useful online tools'),[u,setU]=useState('https://example.com'),[r,setR]=useState('');return <><Field label="Title" value={t} onChange={e=>setT(e.target.value)}/><Field label="Description" value={d} onChange={e=>setD(e.target.value)}/><Field label="Canonical URL" value={u} onChange={e=>setU(e.target.value)}/><Button onClick={()=>setR(`<title>${t}</title>\n<meta name="description" content="${d.replaceAll('"','&quot;')}">\n<link rel="canonical" href="${u}">\n<meta property="og:title" content="${t}">\n<meta property="og:description" content="${d.replaceAll('"','&quot;')}">\n<meta property="og:url" content="${u}">`)}>Generate Tags</Button>{r&&<textarea rows="10" value={r} readOnly/>}</>}
function Sitemap(){const[u,setU]=useState('https://example.com/\nhttps://example.com/about'),[r,setR]=useState('');return <><textarea rows="10" value={u} onChange={e=>setU(e.target.value)}/><Button onClick={()=>setR(`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${u.split(/\n+/).filter(Boolean).map(x=>`  <url><loc>${x.trim()}</loc></url>`).join('\n')}\n</urlset>`)}>Generate Sitemap</Button>{r&&<><textarea rows="12" value={r} readOnly/><Download data={r} name="sitemap.xml" type="application/xml"/></>}</>}
function Strength(){const[p,setP]=useState(''),[r,setR]=useState('');function go(){let s=0;if(p.length>=8)s++;if(p.length>=12)s++;if(/[a-z]/.test(p)&&/[A-Z]/.test(p))s++;if(/\d/.test(p))s++;if(/[^A-Za-z0-9]/.test(p))s++;setR(['Very weak','Weak','Fair','Good','Strong','Excellent'][s])}return <><Field label="Password" type="password" value={p} onChange={e=>setP(e.target.value)}/><Button onClick={go}>Check Strength</Button>{r&&<div className="result">Strength: {r}</div>}</>}
function Clock(){const zones=['Asia/Dhaka','Asia/Kolkata','Asia/Dubai','Europe/London','Europe/Paris','America/New_York','America/Los_Angeles','Asia/Tokyo','Australia/Sydney'];const[t,setT]=useState(Date.now());useEffect(()=>{const i=setInterval(()=>setT(Date.now()),1000);return()=>clearInterval(i)},[]);return <div className="grid">{zones.map(z=><div className="card" key={z}><h3>{z}</h3><p>{new Intl.DateTimeFormat('en-US',{timeZone:z,dateStyle:'medium',timeStyle:'medium'}).format(t)}</p></div>)}</div>}
function Upload({label,...p}){return <label className="upload">{label}<input type="file" {...p}/></label>}
function Tool({slug}){const map={'pdf-merge':<PDFMerge/>,'pdf-split':<PDFSplit/>,'pdf-compressor':<PDFCompress/>,'image-to-pdf':<ImagePDF/>,'passport-photo-maker':<Passport/>,'gpa-calculator':<GPA/>,'emi-calculator':<EMI/>,'salary-calculator':<Salary/>,'tax-vat-calculator':<TaxVAT/>,'invoice-generator':<Invoice/>,'cover-letter-builder':<Cover/>,'qr-scanner':<QRScan/>,'url-shortener':<Shortener/>,'json-formatter':<JSONTool/>,'favicon-generator':<Favicon/>,'meta-tag-generator':<Meta/>,'sitemap-generator':<Sitemap/>,'password-strength-checker':<Strength/>,'world-clock':<Clock/>};return map[slug]||<p>Tool not found.</p>}
export default function ToolClient({slug}){const m=META[slug]||['Tool not found',''];return <><header><Link className="brand" href="/"><b>Q</b> QuickToolBox</Link><Link href="/">← All tools</Link></header><main className="tool"><small>FREE ONLINE TOOL</small><h1>{m[0]}</h1><p>{m[1]}</p><div className="box"><Tool slug={slug}/></div></main><footer>© 2026 QuickToolBox</footer></>}
